#!/bin/sh

echo " "
echo "//-----------------------------//"
echo "Running formatter for Rust code"
echo "//-----------------------------//"
echo " "
cargo fmt
echo "\033[0;32mFormatting done...\033[0m"
echo " "

echo "//-----------------------------//"
echo "Running automatic clippy fixes"
echo "//-----------------------------//"
echo " "
cargo clippy --fix
git add -A
echo "\033[0;32mClippy fixes done...\033[0m"
echo " "

echo "//-----------------------------//"